name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    name: Build, test, check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt, clippy
      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git/
            ~/.cargo/registry/
            target/
          key: ${{ runner.os }}-typewriters-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-typewriters
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
